"""init

Revision ID: 01e854c05c11
Revises: 401ebf63f963
Create Date: 2026-01-15 05:33:31.191771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e854c05c11'
down_revision: Union[str, Sequence[str], None] = '401ebf63f963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('receicer_content', sa.String(length=200), nullable=False, comment='被通知者的文章/评论内容'))
    op.drop_column('interactive_messages', 'receiver_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('receiver_content', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='被通知者的文章/评论内容'))
    op.drop_column('interactive_messages', 'receicer_content')
    # ### end Alembic commands ###
