"""init

Revision ID: 1104b16b021e
Revises: 962e81f36529
Create Date: 2026-01-16 03:59:02.530009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1104b16b021e'
down_revision: Union[str, Sequence[str], None] = '962e81f36529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('articles', sa.Column('year', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'year')
    op.drop_column('articles', 'gender')
    # ### end Alembic commands ###
