"""add icon

Revision ID: 175f7db121dc
Revises: f7f90f86b029
Create Date: 2026-01-02 17:56:20.120865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175f7db121dc'
down_revision: Union[str, Sequence[str], None] = 'f7f90f86b029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('icon', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'icon')
    # ### end Alembic commands ###
