"""init

Revision ID: 20b1de7da181
Revises: f4f10d1dc1bc
Create Date: 2026-01-15 03:14:16.027535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20b1de7da181'
down_revision: Union[str, Sequence[str], None] = 'f4f10d1dc1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('img', sa.String(length=200), nullable=True, comment='图片URL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactive_messages', 'img')
    # ### end Alembic commands ###
