"""no

Revision ID: 2351a9360cfc
Revises: c2f6de5a28cd
Create Date: 2026-01-04 22:54:06.135090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2351a9360cfc'
down_revision: Union[str, Sequence[str], None] = 'c2f6de5a28cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('email_codes_email_key'), 'email_codes', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('email_codes_email_key'), 'email_codes', type_='unique')
    # ### end Alembic commands ###
