"""init

Revision ID: 2be65b1d0c88
Revises: 8869204af23f
Create Date: 2026-01-11 01:52:31.204907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2be65b1d0c88'
down_revision: Union[str, Sequence[str], None] = '8869204af23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
