"""init

Revision ID: 371422ea54f8
Revises: bf9de1a7cb70
Create Date: 2026-01-18 00:11:46.627663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371422ea54f8'
down_revision: Union[str, Sequence[str], None] = 'bf9de1a7cb70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactive_messages', 'relate_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_comment='关联业务ID：点赞-文章ID 评论文章-评论ID 点赞评论-评论ID 回复-评论ID/父评论ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactive_messages', 'relate_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_comment='关联业务ID：点赞-文章ID 评论文章-评论ID 点赞评论-评论ID 回复-评论ID/父评论ID',
               existing_nullable=False)
    # ### end Alembic commands ###
