"""init

Revision ID: 3ff2df412b84
Revises: 9618507328e0
Create Date: 2026-01-14 17:02:10.495099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff2df412b84'
down_revision: Union[str, Sequence[str], None] = '9618507328e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 为避免旧数据导致 NOT NULL 违规，分步迁移：先加可空列、回填、再设为非空
    op.add_column('user_details', sa.Column('last_seen_msg_time', sa.DateTime(), nullable=True))
    op.execute("UPDATE user_details SET last_seen_msg_time = NOW() WHERE last_seen_msg_time IS NULL")
    op.alter_column('user_details', 'last_seen_msg_time', existing_type=sa.DateTime(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'last_seen_msg_time')
    # ### end Alembic commands ###
