"""init

Revision ID: 41869bbfb778
Revises: a051ec0b9d8a
Create Date: 2026-01-10 05:32:30.488674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41869bbfb778'
down_revision: Union[str, Sequence[str], None] = 'a051ec0b9d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('user_details', sa.Column('username', sa.String(length=20), nullable=True))
    op.execute("UPDATE user_details ud SET username = u.username FROM users u WHERE u.id = ud.user_id;")
    op.execute("UPDATE user_details SET username = '' WHERE username IS NULL;")
    op.alter_column('user_details', 'username', existing_type=sa.String(length=20), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_details', 'username')
    # ### end Alembic commands ###