"""init

Revision ID: 478a96166277
Revises: 5179f8eff81a
Create Date: 2026-01-15 03:21:11.612604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478a96166277'
down_revision: Union[str, Sequence[str], None] = '5179f8eff81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactive_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='消息接收用户ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='互动发起用户ID'),
    sa.Column('sender_username', sa.String(length=20), nullable=False, comment='发起者用户名'),
    sa.Column('sender_avatar', sa.String(length=200), nullable=False, comment='发起者头像URL'),
    sa.Column('interact_type', sa.Integer(), nullable=False, comment='互动类型：1-文章点赞 2-文章评论 3-评论点赞 4-评论回复'),
    sa.Column('relate_id', sa.Integer(), nullable=False, comment='关联业务ID'),
    sa.Column('content', sa.String(length=200), nullable=False, comment='消息预览内容'),
    sa.Column('img', sa.String(length=200), nullable=True, comment='图片URL'),
    sa.Column('is_read', sa.Integer(), nullable=False, comment='是否已读：0-未读 1-已读'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='消息创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('interactive_messages_pkey'))
    )
    op.create_index('idx_interact_relate', 'interactive_messages', ['interact_type', 'relate_id'], unique=False)
    op.create_index('idx_interactive_sender', 'interactive_messages', ['sender_id'], unique=False)
    op.create_index('idx_receiver_unread_time', 'interactive_messages', ['receiver_id', 'is_read', 'create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receiver_unread_time', table_name='interactive_messages')
    op.drop_index('idx_interactive_sender', table_name='interactive_messages')
    op.drop_index('idx_interact_relate', table_name='interactive_messages')
    op.drop_table('interactive_messages')
    # ### end Alembic commands ###
