"""init

Revision ID: 5179f8eff81a
Revises: 530e9161fdf3
Create Date: 2026-01-15 03:20:33.504435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5179f8eff81a'
down_revision: Union[str, Sequence[str], None] = '530e9161fdf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('sender_username', sa.String(length=20), nullable=False, comment='发起者用户名'))
    op.drop_column('interactive_messages', 'sender_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('sender_nickname', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='发起者昵称'))
    op.drop_column('interactive_messages', 'sender_username')
    # ### end Alembic commands ###
