"""init

Revision ID: 53423398e3c9
Revises: 5c55c99a63bc
Create Date: 2026-01-16 02:37:18.687734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53423398e3c9'
down_revision: Union[str, Sequence[str], None] = '5c55c99a63bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_interact_relate'), table_name='interactive_messages')
    op.drop_index(op.f('idx_interactive_sender'), table_name='interactive_messages')
    op.drop_index(op.f('idx_receiver_unread_time'), table_name='interactive_messages')
    op.create_index('idx_receiver_time', 'interactive_messages', ['receiver_id', 'create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receiver_time', table_name='interactive_messages')
    op.create_index(op.f('idx_receiver_unread_time'), 'interactive_messages', ['receiver_id', 'status', 'create_time'], unique=False)
    op.create_index(op.f('idx_interactive_sender'), 'interactive_messages', ['sender_id'], unique=False)
    op.create_index(op.f('idx_interact_relate'), 'interactive_messages', ['interact_type', 'relate_id'], unique=False)
    # ### end Alembic commands ###
