"""no

Revision ID: 57375930641b
Revises: d462b301e47b
Create Date: 2026-01-08 16:08:57.432839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57375930641b'
down_revision: Union[str, Sequence[str], None] = 'd462b301e47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_views', 'view_duration')
    op.drop_index(op.f('idx_comment_likes_comment_id'), table_name='comment_likes')
    op.drop_index(op.f('idx_comment_likes_user_id'), table_name='comment_likes')
    op.create_index('idx_comment_id', 'comment_likes', ['comment_id'], unique=False)
    op.create_index('idx_user_id', 'comment_likes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id', table_name='comment_likes')
    op.drop_index('idx_comment_id', table_name='comment_likes')
    op.create_index(op.f('idx_comment_likes_user_id'), 'comment_likes', ['user_id'], unique=False)
    op.create_index(op.f('idx_comment_likes_comment_id'), 'comment_likes', ['comment_id'], unique=False)
    op.add_column('article_views', sa.Column('view_duration', sa.INTEGER(), autoincrement=False, nullable=False, comment='浏览时长（秒），默认0'))
    # ### end Alembic commands ###
