"""init

Revision ID: 5c55c99a63bc
Revises: 831a8d7ffaa4
Create Date: 2026-01-15 16:41:15.504000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c55c99a63bc'
down_revision: Union[str, Sequence[str], None] = '831a8d7ffaa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactive_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='消息接收用户ID'),
    sa.Column('receiver_content', sa.String(length=200), nullable=False, comment='被通知者的文章/评论内容'),
    sa.Column('receiver_img', sa.String(length=200), nullable=True, comment='被通知者的内容图片'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='互动发起用户ID'),
    sa.Column('sender_username', sa.String(length=20), nullable=False, comment='发起者用户名'),
    sa.Column('sender_avatar', sa.String(length=200), nullable=False, comment='发起者头像URL'),
    sa.Column('interact_type', sa.Integer(), nullable=False, comment='互动类型：1-文章点赞 2-文章评论 3-评论点赞 4-评论回复'),
    sa.Column('relate_id', sa.Integer(), nullable=False, comment='关联业务ID'),
    sa.Column('sender_content', sa.String(length=200), nullable=False, comment='发起者互动内容预览'),
    sa.Column('sender_img', sa.String(length=200), nullable=True, comment='发起者互动图片URL'),
    sa.Column('status', sa.Integer(), nullable=False, comment='消息状态：0-未读 1-已读'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='消息创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('interactive_messages_pkey'))
    )
    op.create_index('idx_interact_relate', 'interactive_messages', ['interact_type', 'relate_id'], unique=False)
    op.create_index('idx_interactive_sender', 'interactive_messages', ['sender_id'], unique=False)
    op.create_index('idx_receiver_unread_time', 'interactive_messages', ['receiver_id', 'status', 'create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receiver_unread_time', table_name='interactive_messages')
    op.drop_index('idx_interactive_sender', table_name='interactive_messages')
    op.drop_index('idx_interact_relate', table_name='interactive_messages')
    op.drop_table('interactive_messages')
    # ### end Alembic commands ###
