"""init

Revision ID: 7c76f4d9b54b
Revises: 2be65b1d0c88
Create Date: 2026-01-11 16:22:30.514975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c76f4d9b54b'
down_revision: Union[str, Sequence[str], None] = '2be65b1d0c88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('status', sa.Integer(), nullable=True))
    op.execute("UPDATE comments SET status = CASE WHEN is_deleted THEN 1 ELSE 0 END")
    op.alter_column('comments', 'status', nullable=False)
    op.drop_column('comments', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.execute("UPDATE comments SET is_deleted = CASE WHEN status = 1 THEN TRUE ELSE FALSE END")
    op.alter_column('comments', 'is_deleted', nullable=False)
    op.drop_column('comments', 'status')
    # ### end Alembic commands ###
