"""init

Revision ID: 962e81f36529
Revises: 98e8d8cdd34b
Create Date: 2026-01-16 03:44:06.667764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '962e81f36529'
down_revision: Union[str, Sequence[str], None] = '98e8d8cdd34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('username', sa.String(length=20), nullable=True))
    op.add_column('articles', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.execute("UPDATE articles SET username = COALESCE(username, ''), avatar = COALESCE(avatar, '')")
    op.execute(
        """
        UPDATE articles a
        SET username = COALESCE(ud.username, ''),
            avatar   = COALESCE(ud.avatar, '')
        FROM user_details ud
        WHERE ud.user_id = a.user_id;
        """
    )
    op.alter_column('articles', 'username', existing_type=sa.String(length=20), nullable=False)
    op.alter_column('articles', 'avatar', existing_type=sa.String(length=200), nullable=False)
    op.drop_index(op.f('idx_receiver_status_time'), table_name='interactive_messages')
    op.create_index('idx_receiver_status', 'interactive_messages', ['receiver_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receiver_status', table_name='interactive_messages')
    op.create_index(op.f('idx_receiver_status_time'), 'interactive_messages', ['receiver_id', 'status', 'create_time'], unique=False)
    op.drop_column('articles', 'avatar')
    op.drop_column('articles', 'username')
    # ### end Alembic commands ###
