"""init

Revision ID: b117e04cc527
Revises: daa260cba197
Create Date: 2026-01-16 17:17:29.624884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b117e04cc527'
down_revision: Union[str, Sequence[str], None] = 'daa260cba197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Add columns as nullable first
    op.add_column('comments', sa.Column('username', sa.String(length=20), nullable=True))
    op.add_column('comments', sa.Column('avatar', sa.String(length=200), nullable=True))
    
    # 2. Backfill data from user_details
    # Note: syntax depends on the DB dialect. Assuming SQLite or PostgreSQL-compatible generic SQL for this simple case.
    # For SQLite, direct UPDATE with FROM/JOIN might be limited, so we use a correlated subquery.
    op.execute("""
        UPDATE comments
        SET username = (SELECT username FROM user_details WHERE user_details.user_id = comments.user_id),
            avatar = (SELECT avatar FROM user_details WHERE user_details.user_id = comments.user_id)
    """)

    # 3. Handle remaining nulls (if any user_details were missing)
    op.execute("UPDATE comments SET username = 'Unknown' WHERE username IS NULL")
    op.execute("UPDATE comments SET avatar = '' WHERE avatar IS NULL")

    # 4. Alter columns to be non-nullable
    with op.batch_alter_table('comments') as batch_op:
        batch_op.alter_column('username', nullable=False)
        batch_op.alter_column('avatar', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'avatar')
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
