"""init

Revision ID: b398c746bfde
Revises: 4a5af808e5a5
Create Date: 2026-01-15 04:44:22.852095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b398c746bfde'
down_revision: Union[str, Sequence[str], None] = '4a5af808e5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('receicer_content', sa.String(length=200), nullable=False, comment='被通知者的文章/评论内容'))
    op.add_column('interactive_messages', sa.Column('receiver_img', sa.String(length=200), nullable=True, comment='被通知者的内容图片'))
    op.add_column('interactive_messages', sa.Column('sender_content', sa.String(length=200), nullable=False, comment='发起者互动内容预览'))
    op.add_column('interactive_messages', sa.Column('sender_img', sa.String(length=200), nullable=True, comment='发起者互动图片URL'))
    op.drop_column('interactive_messages', 'img')
    op.drop_column('interactive_messages', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactive_messages', sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='消息预览内容'))
    op.add_column('interactive_messages', sa.Column('img', sa.VARCHAR(length=200), autoincrement=False, nullable=True, comment='图片URL'))
    op.drop_column('interactive_messages', 'sender_img')
    op.drop_column('interactive_messages', 'sender_content')
    op.drop_column('interactive_messages', 'receiver_img')
    op.drop_column('interactive_messages', 'receicer_content')
    # ### end Alembic commands ###
