"""table

Revision ID: d462b301e47b
Revises: 43258f63c86a
Create Date: 2026-01-06 02:22:29.062400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd462b301e47b'
down_revision: Union[str, Sequence[str], None] = '43258f63c86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='点赞记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='点赞用户ID'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='被点赞的文章ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='点赞时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('article_likes_pkey')),
    sa.UniqueConstraint('user_id', 'article_id', name='uk_user_article')
    )
    op.create_index('idx_article_likes_article_id', 'article_likes', ['article_id'], unique=False)
    op.create_index('idx_article_likes_user_id', 'article_likes', ['user_id'], unique=False)
    op.create_table('article_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='浏览记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='浏览用户ID（匿名用户可填0）'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='被浏览的文章ID'),
    sa.Column('view_time', sa.DateTime(), nullable=False, comment='浏览时间'),
    sa.Column('view_duration', sa.Integer(), nullable=False, comment='浏览时长（秒），默认0'),
    sa.PrimaryKeyConstraint('id', name=op.f('article_views_pkey'))
    )
    op.create_index('idx_article_views_article_id', 'article_views', ['article_id'], unique=False)
    op.create_index('idx_article_user', 'article_views', ['article_id', 'user_id'], unique=False)
    op.create_index('idx_article_views_user_id', 'article_views', ['user_id'], unique=False)
    op.create_index('idx_article_views_view_time', 'article_views', ['view_time'], unique=False)
    op.create_table('comment_likes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='点赞记录ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='点赞用户ID'),
    sa.Column('comment_id', sa.Integer(), nullable=False, comment='被点赞的评论ID'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='点赞时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('comment_likes_pkey')),
    sa.UniqueConstraint('user_id', 'comment_id', name='uk_user_comment')
    )
    op.create_index('idx_comment_likes_comment_id', 'comment_likes', ['comment_id'], unique=False)
    op.create_index('idx_comment_likes_user_id', 'comment_likes', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey'))
    )
    op.create_index('idx_comments_article_parent', 'comments', ['article_id', 'parent_id'], unique=False)
    op.create_index('idx_comments_parent_id', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_parent_id', table_name='comments')
    op.drop_index('idx_comments_article_parent', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_comment_likes_user_id', table_name='comment_likes')
    op.drop_index('idx_comment_likes_comment_id', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index('idx_article_views_view_time', table_name='article_views')
    op.drop_index('idx_article_views_user_id', table_name='article_views')
    op.drop_index('idx_article_user', table_name='article_views')
    op.drop_index('idx_article_views_article_id', table_name='article_views')
    op.drop_table('article_views')
    op.drop_index('idx_article_likes_user_id', table_name='article_likes')
    op.drop_index('idx_article_likes_article_id', table_name='article_likes')
    op.drop_table('article_likes')
    # ### end Alembic commands ###
