"""init

Revision ID: daa260cba197
Revises: 44d01253cfa6
Create Date: 2026-01-16 04:30:34.079571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa260cba197'
down_revision: Union[str, Sequence[str], None] = '44d01253cfa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactive_messages', 'receiver_content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=5000),
               existing_comment='被通知者的文章/评论内容',
               existing_nullable=False)
    op.alter_column('interactive_messages', 'sender_content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=5000),
               existing_comment='发起者互动内容预览',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactive_messages', 'sender_content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=200),
               existing_comment='发起者互动内容预览',
               existing_nullable=False)
    op.alter_column('interactive_messages', 'receiver_content',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=200),
               existing_comment='被通知者的文章/评论内容',
               existing_nullable=False)
    # ### end Alembic commands ###
