"""init

Revision ID: ea3e9cb75686
Revises: 26e6bb22135e
Create Date: 2025-12-19 18:47:09.239119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3e9cb75686'
down_revision: Union[str, Sequence[str], None] = '26e6bb22135e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('points_name_key'), 'points', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('points_name_key'), 'points', type_='unique')
    # ### end Alembic commands ###
