"""init

Revision ID: f2ef8f164ac1
Revises: 53423398e3c9
Create Date: 2026-01-16 03:08:36.697559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2ef8f164ac1'
down_revision: Union[str, Sequence[str], None] = '53423398e3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_receiver_status_time', 'interactive_messages', ['receiver_id', 'status', 'create_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_receiver_status_time', table_name='interactive_messages')
    # ### end Alembic commands ###
