"""init

Revision ID: f4f10d1dc1bc
Revises: bd78f7a3d663
Create Date: 2026-01-15 01:54:05.953603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4f10d1dc1bc'
down_revision: Union[str, Sequence[str], None] = 'bd78f7a3d663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactive_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='消息ID'),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='消息接收用户ID'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='互动发起用户ID'),
    sa.Column('sender_nickname', sa.String(length=20), nullable=False, comment='发起者昵称'),
    sa.Column('sender_avatar', sa.String(length=200), nullable=False, comment='发起者头像URL'),
    sa.Column('interact_type', sa.Integer(), nullable=False, comment='互动类型：1-文章点赞 2-文章评论 3-评论点赞 4-评论回复'),
    sa.Column('relate_id', sa.Integer(), nullable=False, comment='关联业务ID'),
    sa.Column('content', sa.String(length=200), nullable=False, comment='消息预览内容'),
    sa.Column('is_read', sa.Integer(), nullable=False, comment='是否已读：0-未读 1-已读'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='消息创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('interactive_messages_pkey'))
    )
    op.create_index('idx_interact_relate', 'interactive_messages', ['interact_type', 'relate_id'], unique=False)
    op.create_index('idx_interactive_sender', 'interactive_messages', ['sender_id'], unique=False)
    op.create_index('idx_receiver_unread_time', 'interactive_messages', ['receiver_id', 'is_read', 'create_time'], unique=False)
    op.drop_column('user_details', 'last_seen_msg_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('last_seen_msg_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index('idx_receiver_unread_time', table_name='interactive_messages')
    op.drop_index('idx_interactive_sender', table_name='interactive_messages')
    op.drop_index('idx_interact_relate', table_name='interactive_messages')
    op.drop_table('interactive_messages')
    # ### end Alembic commands ###
