"""modify point

Revision ID: f7f90f86b029
Revises: ea3e9cb75686
Create Date: 2026-01-01 01:58:08.145286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7f90f86b029'
down_revision: Union[str, Sequence[str], None] = 'ea3e9cb75686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points', sa.Column('category', sa.String(length=20), nullable=True))
    op.add_column('points', sa.Column('description', sa.String(length=200), nullable=True))
    op.add_column('points', sa.Column('img', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points', 'img')
    op.drop_column('points', 'description')
    op.drop_column('points', 'category')
    # ### end Alembic commands ###
